version: '3.4'

services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: always
    expose:
      - 5000
      - 8081
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data
    networks:
      - backend

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports: 
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nexus-ssl:/etc/ssl/certs
    networks:
      - backend
    depends_on:
      - nexus
    

networks:
  backend:
    driver: bridge





      


